### Listar barrios filtrados
GET http://localhost:3000/api/barrios/filtrados?nombre=nuevo&page=1&limit=10


### Obtener todos los barrios
GET http://localhost:3000/api/barrios

### obtenr barrio por id
GET http://localhost:3000/api/barrios/1

### Crear un barrio
POST http://localhost:3000/api/barrios
Content-Type: application/json

{
  "nombre": "Nuevo Barrio 3",
  "zona_id": 1
}

### Editar un barrio (por ID)
PUT http://localhost:3000/api/barrios/9
Content-Type: application/json

{
  "nombre": "Barrio completado 2",
  "zona_id": 1
}

### Eliminar un barrio (por ID)
DELETE http://localhost:3000/api/barrios/2
